apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
    - default:
        memory: 512MB
        cpu: 1
      defaultRequest:
        memory: 256MB
        cpu: 0.5
      type: Container