apiVersion: v1
kind: Pod
metadata:
  name: my-custom-scheduler
  namespace: kube-system
  labels:
spec:
  containers:
    - command:
        - kube-scheduler
        - --address=127.0.0.1
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --scheduler-name=my-custom-scheduler
        - --leader-elect=true
        - --lock-object-name=my-custom-scheduler

      name: kube-scheduler
      image: k8s.gcr.io/kube-scheduler-amd64:v1.11v3
